SELECT TRAIN_NO FROM TTS_HISTORY WHERE TRANS_ID=7005;

SELECT SEATS FROM TTS_HISTORY WHERE TRANS_ID=7005;

SELECT PAYMENT_ID  FROM TTS_PAYMENT WHERE TRANS_ID=7005;

SELECT*FROM TTS_HISTORY;

SELECT*FROM TTS_PAYMENT;

SELECT*FROM TTS_TRAIN;

SELECT HIS.TRAIN_NO INTO FLG3TRAINNO,TTS_PAYMENT.PAYMENT_ID INTO PAYMENTID FROM TTS_HISTORY HIS,TTS_PAYMENT PAYM 
WHERE HIS.TRANS_ID=FLG3TRANSID AND PAYM.TRANS_ID=FLG3TRANSID ;

SELECT*FROM TTS_HISTORY HIS,TTS_PAYMENT PAYM  ;

SELECT*FROM EMPLOYEES EMP,DEPARTMENTS DEPT WHERE EMP.EMPLOYEE_ID=DEPT.MANAGER_ID;

SELECT COUNT(*) FROM TTS_PAYMENT WHERE CUSTOMER_ID=6000 AND PAYMENT_STATUS ='ACTIVE';



DECLARE
PAYMNTDT TIMESTAMP ;
BEGIN
FOR I IN (SELECT PAYMENT_ID FROM TTS_PAYMENT) LOOP
SELECT PAYMENT_dATE INTO PAYMNTDT FROM TTS_PAYMENT WHERE PAYMENT_ID=I.PAYMENT_ID;
DBMS_OUTPUT.PUT_LINE(PAYMNTDT);
END LOOP;
END;
/

SELECT PAYMENT_DATE + INTERVAL '5' MINUTE FROM TTS_PAYMENT;

BEGIN
IF(SELECT PAYMENT_DATE FROM TTS_PAYMENT = SELECT PAYMENT_DATE+INTERVAL '5' MINUTE FROM TTS_PAYMENT) THEN
END;
/

SELECT SYSDATE FROM DUAL;

SELECT EXTRACT(MINUTE FROM SYSTIMESTAMP)
FROM dual;

SELECT TO_CHAR(PAYMENT_DATE,'HH12:MI') FROM TTS_PAYMENT;

SELECT TO_CHAR(SYSDATE,'HH12:MI') FROM DUAL;

SELECT TO_CHAR(TO_date('12-FEB-25 13:48:54 ','dd-mm-yy HH24:mi:ss'),'HH24:MI')-TO_cHAR(TO_DATE(SYSDATE,'dd-mm-yy HH24:mi:ss'),'HH:MI') from dual;

SELECT TO_CHAR(TO_date('12-FEB-25 1:48:54  ','dd-mm-yy HH24:mi:ss'),'HH24:MI') FROM DUAL;



SELECT CASE WHEN PAYMENT_DATE+INTERVAL '1'  MINUTE>=SYSTIMESTAMP THEN '0' ELSE '1' END FROM (SELECT PAYMENT_dATE FROM TTS_PAYMENT WHERE PAYMENT_STATUS='PENDING');


SELECT PAYMENT_DATE FROM TTS_PAYMENT;

SELECT SYSDATE FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;

--PROECUDURE TO DELETE PENDING STATUS ABOVE 5MIN
CREATE OR REPLACE PROCEDURE SP_DELETE_PENDINGSTS AS
CND NUMBER;
BEGIN
SELECT CASE WHEN PAYMENT_DATE+INTERVAL '1'  MINUTE>=SYSTIMESTAMP THEN '0' ELSE '1' END INTO CND FROM (SELECT PAYMENT_dATE FROM TTS_PAYMENT WHERE PAYMENT_STATUS='PENDING');
IF CND=1 THEN 
DELETE TTS_PAYMENT WHERE PAYMENT_STATUS='PENDING';
END IF;
END;
/

EXEC SP_DELETE_PENDINGSTS;

BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME=>'DELETE_PENDING_STATUS',
JOB_TYPE=>'STORED_PROCEDURE',
JOB_ACTION=>'SP_DELETE_PENDINGSTS',
START_DATE=>'25-FEB-25 12:07:05 PM',
REPEAT_INTERVAL=>'FREQ=SECONDLY;INTERVAL=20',
END_DATE=>'1-JAN-2026 12:00:00 AM',
AUTO_DROP=>TRUE,
COMMENTS=>'DONE.'
);
END;
/

SELECT SYSDATE+TO_CHAR(SYSDATE,'') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY')+5 FROM DUAL;

SELECT SYSDATE FROM DUAL;


SELECT*FROM USER_SCHEDULER_JOBS;

EXEC DBMS_SCHEDULER.ENABLE('DELETE_PENDING_STATUS');

DECLARE
CND NUMBER;
BEGIN
SELECT CASE WHEN PAYMENT_DATE+INTERVAL '2'  MINUTE>SYSTIMESTAMP THEN '0' ELSE '1' END INTO CND FROM (SELECT PAYMENT_dATE FROM TTS_PAYMENT WHERE PAYMENT_STATUS='PENDING');
DBMS_OUTPUT.PUT_LINE(CND);
END;
/

